#!/usr/bin/perl -w

use Implementor;
use UniLang::Agent::Agent;
use UniLang::Util::Message;

# $UNIVERSAL::agent = UniLang::Agent::Agent->new
#   (Name => "System-Implementor",
#    ReceiveHandler => \&Receive);
$UNIVERSAL::implementor = Implementor->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::implementor->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::implementor->Execute;
